spring:
  application:
    name: sentinel-token-server
server:
  port: 11112

nacos:
  config:
    auto-refresh: true
    group: SENTINEL_GROUP
    bootstrap:
      enable: true
    type: json
    server-addr: 127.0.0.1:8848
    namespace: sentinelTest
    data-id: appA-flow-rules
zookeeper:
  address: localhost:2181